<?php

return [
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    [
        'name' => 'Mario',
        'lastname' => 'Rossi',
        'phone_number' => '333 1234567',
        'email' => 'mario.rossi@email.com',
        'address' => 'Via Roma 1',
        'total_price' => 50.00,
    ],
    [
        'name' => 'Luigi',
        'lastname' => 'Bianchi',
        'phone_number' => '335 7654321',
        'email' => 'luigi.bianchi@email.com',
        'address' => 'Corso Italia 100',
        'total_price' => 75.00,
    ],
    [
        'name' => 'Anna',
        'lastname' => 'Verdi',
        'phone_number' => '338 9876543',
        'email' => 'anna.verdi@email.com',
        'address' => 'Piazza San Marco 1',
        'total_price' => 60.00,
    ],
    [
        'name' => 'Paolo',
        'lastname' => 'Gialli',
        'phone_number' => '339 5432107',
        'email' => 'paolo.gialli@email.com',
        'address' => 'Via Veneto 119',
        'total_price' => 80.00,
    ],
    [
        'name' => 'Maria',
        'lastname' => 'Blu',
        'phone_number' => '340 8765432',
        'email' => 'maria.blu@email.com',
        'address' => 'Lungotevere dei Cadorna 34',
        'total_price' => 55.00,
    ],
    [
        'name' => 'Alessandro',
        'lastname' => 'Verde',
        'phone_number' => '331 2345678',
        'email' => 'alessandro.verde@email.com',
        'address' => 'Via Nazionale 132',
        'total_price' => 70.00,
    ],
    [
        'name' => 'Beatrice',
        'lastname' => 'Arancione',
        'phone_number' => '332 3456789',
        'email' => 'beatrice.arancione@email.com',
        'address' => 'Piazza del Popolo 15',
        'total_price' => 65.00,
    ],
    [
        'name' => 'Carlo',
        'lastname' => 'Viola',
        'phone_number' => '333 4567890',
        'email' => 'carlo.viola@email.com',
        'address' => 'Via del Corso 200',
        'total_price' => 90.00,
    ],
    [
        'name' => 'Elisa',
        'lastname' => 'Gialla',
        'phone_number' => '334 5678901',
        'email' => 'elisa.gialla@email.com',
        'address' => 'Piazza San Giovanni 1',
        'total_price' => 85.00,
    ],
    [
        'name' => 'Fabio',
        'lastname' => 'Rosso',
        'phone_number' => '335 6789012',
        'email' => 'fabio.rosso@email.com',
        'address' => 'Via del Teatro 150, 00185 Roma',
        'total_price' => 95.00,
    ],
    
];
